# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f474e62c665204ff426b778decc499e1"
name = "Upsell-app"
application_url = "https://brandsbro-upsell.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_orders,read_orders"

[auth]
redirect_urls = [ "https://brandsbro-upsell.onrender.com/auth/callback" ]
