export const loader = () => {
  const js = [
    "(function() {",
    "var appUrl = 'https://brandsbro-upsell.onrender.com';",
    "var shopDomain = (window.Shopify && window.Shopify.shop) || new URLSearchParams(window.location.search).get('shop');",
    "if (!shopDomain) return;",
    "var upsellProducts = [];",
    "function loadUpsellProducts(cb) {",
    "  fetch(appUrl + '/api/cart-upsell?shop=' + shopDomain).then(function(r){return r.json();}).then(function(d){",
    "    upsellProducts = d.products || [];",
    "    cb(upsellProducts);",
    "  }).catch(function(){cb([]);});",
    "}",
    "function buildWidget(products) {",
    "  var w = document.createElement('div');",
    "  w.id = 'bb-cart-upsell-widget';",
    "  w.style.cssText = 'padding:16px;border-top:1px solid #e5e5e5;';",
    "  var html = '<p style=\"font-size:13px;font-weight:700;margin:0 0 12px;\">You might also like</p>';",
    "  html += '<div style=\"display:flex;gap:10px;overflow-x:auto;padding-bottom:4px;\">';",
    "  products.forEach(function(p) {",
    "    var vid = p.variantId.split('/').pop();",
    "    html += '<div style=\"flex-shrink:0;width:130px;border:1px solid #e5e5e5;border-radius:8px;overflow:hidden;background:#fff;\">';",
    "    if (p.image) html += '<img src=\"' + p.image + '\" style=\"width:100%;height:90px;object-fit:cover;\"/>';",
    "    html += '<div style=\"padding:8px;\">';",
    "    html += '<p style=\"font-size:11px;font-weight:600;margin:0 0 2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;\">' + p.title + '</p>';",
    "    html += '<p style=\"font-size:11px;color:#666;margin:0 0 6px;\">$' + p.price + '</p>';",
    "    html += '<button id=\"bb-btn-' + vid + '\" onclick=\"bbUpsellAdd(\\'' + vid + '\\')\" style=\"width:100%;background:#000;color:#fff;border:none;border-radius:4px;padding:5px;font-size:11px;font-weight:600;cursor:pointer;\">+ Add</button>';",
    "    html += '</div></div>';",
    "  });",
    "  html += '</div>';",
    "  w.innerHTML = html;",
    "  return w;",
    "}",
    "function injectWidget() {",
    "  if (!upsellProducts.length) return;",
    "  var ex = document.getElementById('bb-cart-upsell-widget');",
    "  if (ex) ex.remove();",
    "  var cd = document.querySelector('cart-drawer');",
    "  if (!cd) return;",
    "  var footer = cd.querySelector('.drawer__footer');",
    "  if (footer) footer.insertBefore(buildWidget(upsellProducts), footer.firstChild);",
    "}",
    "function patchRenderContents() {",
    "  var cd = document.querySelector('cart-drawer');",
    "  if (!cd || cd.__bbPatched) return;",
    "  cd.__bbPatched = true;",
    "  var orig = cd.renderContents.bind(cd);",
    "  cd.renderContents = function(state) { orig(state); setTimeout(injectWidget, 50); };",
    "}",
    "window.bbUpsellAdd = function(variantId) {",
    "  var btn = document.getElementById('bb-btn-' + variantId);",
    "  if (btn) { btn.disabled = true; btn.textContent = 'Adding...'; }",
    "  fetch('/cart/add.js', {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:[{id:parseInt(variantId),quantity:1}]})})",
    "  .then(function(r){return r.json();}).then(function(){",
    "    if (btn) { btn.textContent = 'Added!'; btn.style.background = '#008060'; }",
    "    setTimeout(function(){",
    "      fetch('/?sections=cart-drawer,cart-icon-bubble').then(function(r){return r.json();}).then(function(s){",
    "        var cd = document.querySelector('cart-drawer');",
    "        if (cd && typeof cd.renderContents === 'function') { cd.classList.remove('is-empty'); cd.renderContents({sections:s}); }",
    "        var doc = new DOMParser().parseFromString(s['cart-icon-bubble']||'','text/html');",
    "        var nb = doc.querySelector('.cart-count-bubble');",
    "        var ob = document.querySelector('.cart-count-bubble');",
    "        if (ob && nb) ob.outerHTML = nb.outerHTML;",
    "      });",
    "    }, 800);",
    "    setTimeout(function(){ if(btn){btn.textContent='+ Add';btn.style.background='#000';btn.disabled=false;} }, 2000);",
    "  });",
    "};",
    "function init() {",
    "  loadUpsellProducts(function(products) {",
    "    if (!products.length) return;",
    "    patchRenderContents();",
    "    var cd = document.querySelector('cart-drawer');",
    "    if (cd) {",
    "      new MutationObserver(function(){",
    "        if (cd.classList.contains('active')) { patchRenderContents(); injectWidget(); }",
    "        if (!document.getElementById('bb-cart-upsell-widget') && cd.classList.contains('active')) { injectWidget(); }",
    "      }).observe(cd, {attributes:true, attributeFilter:['class']});",
    "    }",
    "  });",
    "}",
    "if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', init); } else { init(); }",
    "})();"
  ].join("\n");

  return new Response(js, {
    headers: {
      "Content-Type": "application/javascript",
      "Cache-Control": "no-cache",
      "Access-Control-Allow-Origin": "*",
    },
  });
};
